### ISSUE TITLE
Deforminator depends on LoadAllDicomFiles, currently not included in release. 

### ISSUE THREAD

**Issue by ruicarsa** [UCSDPulmonaryImaging/Deforminator#4]

**Comment by UCSDPulmonaryImaging** [comment]
Deforminator multislice depends on LoadAllDicomFiles, which is not contained in the release.  
LoadAllDicomFiles version 5.1 is needed.

**Comment by UCSDPulmonaryImaging** [comment]
Function uploaded, testing needed.
